### DELETE BY ID
DELETE http://localhost:8080/users/1
Accept: application/json

### UPDATE BY ID
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "aby1",
  "role": "se"
}

### GET BY ID
GET http://localhost:8080/users/3
Accept: application/json

### GET ALL
GET http://localhost:8080/users
Accept: application/json

### CREATE
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "aby2",
  "role": "se"
}
###
POST http://localhost:8080/users/register
Content-Type: application/json

{
"name": "aby22",
"role": "se"
}

###


POST http://localhost:8080/checkin/1/2